import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';

import '../models/expense.dart';
import '../providers/settings_provider.dart';

class PdfService {
  /// Generates a tax summary PDF from [startDate] to now, saves it to device storage,
  /// and returns the file path.
  static Future<Uint8List> generateTaxSummaryBytes({
    required List<Expense> allTransactions,
    required SettingsProvider sProv,
    required DateTime startDate,
  }) async {
    final pdf = pw.Document();

    // Load logo
    final ByteData logoData = await rootBundle.load('assets/images/logo1234.png');
    final Uint8List logoBytes = logoData.buffer.asUint8List();

    final cur = sProv.settings.currency;
    final now = DateTime.now();

    // Filter to ledger-affecting transactions within the date range
    final ledgerItems = allTransactions
        .where((e) => e.fundingSource == 'resources' && !e.date.isBefore(startDate) && !e.date.isAfter(now))
        .toList();

    // Sort oldest first for running balance
    ledgerItems.sort((a, b) => a.date.compareTo(b.date));

    // Calculate initial balance
    final double netChange = ledgerItems.fold(0.0, (sum, e) => sum + e.amount);
    final double finalBalance = sProv.settings.availableResources;
    final double initialBalance = finalBalance + netChange;

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          buildBackground: (pw.Context context) => pw.FullPage(
            ignoreMargins: true,
            child: pw.Watermark(
              child: pw.Opacity(
                opacity: 0.04,
                child: pw.Image(pw.MemoryImage(logoBytes), width: 300, height: 300),
              ),
            ),
          ),
        ),
        build: (pw.Context context) {
          return [

            // Header
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Nimbus Spend', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800)),
                    pw.Text('Official Tax & Ledger Summary', style: pw.TextStyle(fontSize: 14, color: PdfColors.grey700)),
                    pw.SizedBox(height: 10),
                    pw.Text('Period: ${DateFormat('MMM dd, yyyy').format(startDate)} — ${DateFormat('MMM dd, yyyy').format(now)}', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
                    pw.Text('Generated: ${DateFormat('MMMM dd, yyyy - HH:mm').format(now)}', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
                    pw.Text('Account: ${sProv.settings.name}', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
                  ],
                ),
                pw.Image(pw.MemoryImage(logoBytes), width: 50, height: 50),
              ],
            ),
            pw.SizedBox(height: 20),

            // Documentation block
            pw.Container(
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey100,
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
                border: pw.Border.all(color: PdfColors.grey300),
              ),
              child: pw.Text(
                'DOCUMENTATION:\n'
                'This document is an official tax-grade ledger summary generated by Nimbus Spend. '
                'It outlines all synchronized financial changes affecting the "Available Resources" liquidity pool. '
                'Negative value amounts indicate deposits (Income/Refunds/Transfers In). '
                'Positive value amounts indicate expenditures (Expenses/Transfers Out). '
                'Running Balance is computed chronologically from the Initial state to the Final state. '
                'This report is intended for personal bookkeeping, tax preparation, and financial auditing purposes.',
                style: pw.TextStyle(fontSize: 9, color: PdfColors.grey800, lineSpacing: 1.5),
              ),
            ),
            pw.SizedBox(height: 20),

            // Balances Summary
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
              children: [
                _buildSummaryBox('Initial Balance', initialBalance, cur),
                _buildSummaryBox('Total Delta', -netChange, cur, isDelta: true),
                _buildSummaryBox('Final Balance', finalBalance, cur),
              ],
            ),
            pw.SizedBox(height: 10),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
              children: [
                _buildSummaryBox('Txn Count', ledgerItems.length.toDouble(), cur, isCount: true),
                _buildSummaryBox('Period (Days)', now.difference(startDate).inDays.toDouble(), cur, isCount: true),
                _buildSummaryBox('Monthly Budget', sProv.settings.monthlyBudget, cur),
              ],
            ),
            pw.SizedBox(height: 30),

            // Ledger Table
            pw.Text('CHRONOLOGICAL LEDGER', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: PdfColors.grey800)),
            pw.SizedBox(height: 10),

            if (ledgerItems.isEmpty)
              pw.Text('No transactions found for the selected period.', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500))
            else
              _buildLedgerTable(ledgerItems, initialBalance, cur),

            pw.SizedBox(height: 30),
            pw.Divider(color: PdfColors.grey300),
            pw.SizedBox(height: 10),
            pw.Text('This document was auto-generated by Nimbus Spend and is not a substitute for professional financial advice.',
              style: pw.TextStyle(fontSize: 8, color: PdfColors.grey400)),
          ];
        },
      ),
    );

    return pdf.save();
  }

  static Future<String> generateTaxSummary({
    required List<Expense> allTransactions,
    required SettingsProvider sProv,
    required DateTime startDate,
  }) async {
    final bytes = await generateTaxSummaryBytes(allTransactions: allTransactions, sProv: sProv, startDate: startDate);
    
    // Save to device storage
    final String folderPath = '/storage/emulated/0/Documents/Nimbus Spend/Summaries';
    final dir = Directory(folderPath);
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }

    final now = DateTime.now();
    final fileName = 'Nimbus_Ledger_${DateFormat('yyyyMMdd_HHmmss').format(now)}.pdf';
    final file = File('$folderPath/$fileName');
    await file.writeAsBytes(bytes);

    return file.path;
  }

  static pw.Widget _buildSummaryBox(String title, double amount, String cur, {bool isDelta = false, bool isCount = false}) {
    final color = isDelta ? (amount >= 0 ? PdfColors.green700 : PdfColors.red700) : PdfColors.blue800;
    final prefix = isDelta ? (amount > 0 ? '+' : '') : '';

    String displayValue;
    if (isCount) {
      displayValue = amount.toInt().toString();
    } else {
      displayValue = '$prefix$cur${amount.abs().toStringAsFixed(2)}';
    }

    return pw.Container(
      width: 120,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        children: [
          pw.Text(title, style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
          pw.SizedBox(height: 6),
          pw.Text(displayValue, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: color)),
        ],
      ),
    );
  }

  static pw.Widget _buildLedgerTable(List<Expense> items, double initial, String cur) {
    double running = initial;

    final headers = ['Date & Time', 'Category', 'Note', 'Amount', 'Running Bal.'];

    final data = items.map((e) {
      final isIncome = e.amount < 0;
      final displayAmount = isIncome ? '+$cur${e.amount.abs().toStringAsFixed(2)}' : '-$cur${e.amount.toStringAsFixed(2)}';
      running -= e.amount;

      return [
        DateFormat('MMM dd, yyyy HH:mm').format(e.date),
        e.category,
        e.note.isNotEmpty ? e.note : '-',
        displayAmount,
        '$cur${running.toStringAsFixed(2)}',
      ];
    }).toList();

    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: data,
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      headerStyle: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.blueGrey800),
      cellStyle: const pw.TextStyle(fontSize: 8),
      cellAlignment: pw.Alignment.centerLeft,
      cellAlignments: {
        3: pw.Alignment.centerRight,
        4: pw.Alignment.centerRight,
      },
      oddRowDecoration: const pw.BoxDecoration(color: PdfColors.grey50),
    );
  }
}
