class NimbusTips {
  static const List<String> tips = [
    // Budgeting Basics
    "A budget is telling your money where to go instead of wondering where it went.",
    "Try the 50/30/20 rule: 50% needs, 30% wants, 20% savings.",
    "Pay yourself first! Transfer money to savings as soon as you get paid.",
    "Tracking your expenses is the first step to financial freedom.",
    "Beware of small expenses; a small leak will sink a great ship.",
    "Review your budget monthly to ensure it aligns with your goals.",
    "Give every dollar a job before the month begins.",
    "Unexpected expenses are expected. Build an emergency fund!",
    "Distinguish between needs and wants before swiping your card.",
    "Don't save what is left after spending; spend what is left after saving.",
    
    // Saving & Emergency Funds
    "Aim to save 3 to 6 months of living expenses for emergencies.",
    "Automate your savings so you don't even have to think about it.",
    "A high-yield savings account earns you money while you sleep.",
    "Save for big purchases in advance rather than using credit.",
    "Start small: even saving \$10 a week adds up over time.",
    "Keep your emergency fund easily accessible, but not so easy you spend it on pizza.",
    "Found an extra \$20? Put half in savings, spend half guilt-free.",
    "When you get a raise, increase your savings rate first.",
    "Challenge yourself to a 'no-spend' weekend once a month.",
    "Cancel unused subscriptions and put that money directly into savings.",
    
    // Debt Management
    "The snowball method: pay off smallest debts first for quick wins.",
    "The avalanche method: pay off highest interest debts first to save money.",
    "Always pay more than the minimum balance on your credit cards.",
    "Compound interest is the 8th wonder of the world. Make it work FOR you, not against you.",
    "If you can't afford to pay cash for it, you probably can't afford it.",
    "Consolidate high-interest debt if you can get a lower rate.",
    "Call your credit card company and ask for a lower interest rate. It works!",
    "Credit cards are tools, not free money.",
    "Never carry a balance just to 'build credit'. That's a myth.",
    "Treat your credit card like a debit card.",
    
    // Shopping & Spending Habits
    "Wait 24 hours before making a non-essential purchase.",
    "Unsubscribe from promotional emails to reduce temptation.",
    "Delete your saved credit card info from online stores.",
    "Calculate the cost of an item in 'hours worked' instead of dollars.",
    "Never go grocery shopping when you're hungry.",
    "Buy generic brands for staples; you're often just paying for marketing.",
    "Quality over quantity: buying one good pair of shoes is cheaper than replacing cheap ones.",
    "Look for used items before buying new. Thrift stores and marketplaces are goldmines.",
    "Embrace minimalism. Less stuff = less stress + more money.",
    "Are you buying this because you need it, or because it's on sale?",
    
    // Investing & Growth
    "The best time to plant a tree was 20 years ago. The second best time is now. Start investing!",
    "Time in the market beats timing the market.",
    "Take advantage of employer matches on retirement accounts. It's free money!",
    "Diversification is the only free lunch in investing.",
    "Don't check your investment portfolio every day if it causes you stress.",
    "Invest in yourself through books, courses, and skills.",
    "Understand what you are investing in before putting money down.",
    "Start an index fund to capture the growth of the overall market.",
    "As your income grows, avoid lifestyle creep.",
    "Compound interest rewards the patient.",
    
    // Psychology of Money
    "Money buys choices, not just things.",
    "Comparing your finances to others is a losing game.",
    "It's okay to spend money on things that truly bring you joy.",
    "Forgive yourself for past money mistakes. Today is a new start.",
    "Talk about money with your partner. Communication is key.",
    "Does this purchase align with your long-term goals?",
    "Don't let money define your self-worth.",
    "Generosity feels good. Budget a small amount for giving.",
    "Financial independence is about freedom, not necessarily retiring early.",
    "Stress about money is normal. Taking action reduces the stress.",
    
    // Income & Career
    "Negotiate your salary. The worst they can say is no.",
    "Multiple streams of income provide financial security.",
    "Your current job doesn't have to be your forever job.",
    "Build a side hustle doing something you genuinely enjoy.",
    "Keep your resume updated even if you aren't actively looking.",
    "Networking is an investment in your future earning potential.",
    "Ask for a raise if you've taken on more responsibilities.",
    "Keep learning new skills to stay competitive in your field.",
    "Turn a hobby into a small income stream.",
    "Your greatest wealth-building tool is your income.",
    
    // Planning for the Future
    "Write down your financial goals and put them where you can see them.",
    "Create a will. Even if you don't have much, it's important.",
    "Check your credit report annually for free.",
    "Review your insurance coverages yearly to ensure they meet your needs.",
    "Start a sinking fund for expected yearly expenses like holidays.",
    "Plan for retirement like you'll live to be 100.",
    "Set up a 'fun money' fund so you can splurge without guilt.",
    "Automate your bill payments to avoid late fees.",
    "Rebalance your investment portfolio once a year.",
    "Teach your kids about money early. It's a vital life skill.",

    // Daily Micro-habits
    "Make your own coffee. Those \$5 lattes add up!",
    "Pack a lunch instead of eating out.",
    "Drink water when eating out instead of buying a beverage.",
    "Check your bank balance daily so there are no surprises.",
    "Use cash for discretionary spending to literally feel the money leaving your hands.",
    "Turn off lights and unplug appliances to save on utilities.",
    "Borrow books from the library instead of buying them.",
    "Use a list when grocery shopping and stick to it.",
    "Maintain your car and home regularly to avoid costly repairs later.",
    "Review all recurring charges on your card statement this month.",

    // Advanced Strategies
    "Harvest tax losses if you have taxable investments.",
    "Look into HSA accounts if you have a high deductible health plan.",
    "Understand the difference between good debt (building equity) and bad debt.",
    "Max out your Roth IRA if you qualify.",
    "Consider the lifetime cost of a pet before adopting.",
    "Don't let tax refunds feel like a bonus; it's your money being returned to you.",
    "Avoid the \"sunk cost fallacy\". If a subscription isn't worth it anymore, cancel it.",
    "Before signing a lease, calculate total monthly costs including utilities and commute.",
    "If you get a bonus, treat yourself slightly, but save/invest the rest.",
    "Read the fine print on any financial agreement.",

    // Nimbus Specific Motivation
    "I'll keep watching your spending patterns. You've got this! ☁️",
    "Logging expenses manually builds mindfulness. Great job holding yourself accountable. 💙",
    "Don't let a bad spending day ruin your week. Clouds pass! 🌤️",
    "I may just be a cloud, but I think you're doing great. ✨",
    "Check your Available Resources before making that next big purchase!",
    "Your monthly allowance is your safety net. Keep an eye on the limit.",
    "Debt isn't the end of the world. Set up a payment plan and crush it! 💳",
    "Have you checked your subscriptions recently? Let's make sure there are no ghosts draining you.",
    "Remember, health and happiness are your true ultimate resources.",
    "I'm always floating by if you need a reminder to stay focused! 💫",

    // More general tips to reach ~200
    "A warranty is often not worth the price. Self-insure instead by keeping savings.",
    "Review your cell phone plan. You might be paying for data you don't use.",
    "Switching auto insurance providers every few years can save you hundreds.",
    "Buy out-of-season clothing to get the steepest discounts.",
    "Eat leftovers! Food waste is literally throwing money away.",
    "Learn basic home repairs from YouTube to save on contractors.",
    "Avoid ATM fees by planning ahead and using your bank's network.",
    "A free trial is only free if you remember to cancel it.",
    "Share streaming services with family members if the terms allow it.",
    "Use the 30-day rule: wait 30 days before making a big purchase.",
    "Cook in bulk and freeze meals for nights when you're too tired to cook.",
    "Track your net worth. It's the ultimate scoreboard of your finances.",
    "Don't put off going to the dentist. Preventative care is cheaper than a root canal.",
    "If it sounds too good to be true, it probably is.",
    "Buy a reliable used car over a brand new one to avoid immediate depreciation.",
    "Don't finance a car for more than 48 months.",
    "Keep your tires properly inflated to improve gas mileage.",
    "Refinance your mortgage if rates drop significantly.",
    "Use a programmable thermostat to save on heating and cooling.",
    "Avoid \"Buy Now, Pay Later\" schemes; they encourage spending money you don't have.",
    "Don't use payday loans. The interest rates are predatory.",
    "A hobby shouldn't put you into debt.",
    "Declutter your home and sell items you no longer use.",
    "Rent equipment you only need once instead of buying it.",
    "Take your own snacks on road trips to avoid gas station markups.",
    "Drink more water. It's good for your health and your wallet if you substitute it for soda.",
    "Walk or bike for short trips instead of driving.",
    "Meal plan for the week before you grocery shop.",
    "Check unit prices at the grocery store. Bigger isn't always cheaper.",
    "Take advantage of credit card rewards, but only if you pay the balance in full.",
    "Don't cosign loans for family or friends unless you are prepared to pay the whole thing.",
    "Investing is a marathon, not a sprint.",
    "Don't borrow from your 401(k) unless it's a true emergency.",
    "Build a career fund to cover conferences, courses, or certifications.",
    "Have regular 'money dates' with your partner to stay aligned on goals.",
    "Keep your receipts for major purchases in case of warranties or returns.",
    "Use browser extensions to find promo codes when shopping online.",
    "Clear your browser cookies when searching for flights.",
    "Fly on Tuesdays or Wednesdays for cheaper airfare.",
    "Travel during the shoulder season to save on accommodation.",
    "Don't buy flight insurance from the airline; get comprehensive travel insurance instead.",
    "Calculate your real hourly wage (after commute, taxes, and work expenses).",
    "Don't upgrade your phone every year. Keep it until it stops working.",
    "Repair clothes instead of immediately tossing them.",
    "Learn to cut your own hair or use a cheaper barber.",
    "Host potlucks instead of going out to dinner with friends.",
    "Cut the cord on cable and stick to one or two streaming services.",
    "Cancel gym memberships you don't use; run outside or use free home workout videos.",
    "Don't grocery shop when you're emotional.",
    "If you get a tax refund, treat a small percentage as fun money, save the rest.",
    "Automate your investments. Make wealth building inevitable.",
    "Read one personal finance book a year.",
    "Listen to personal finance podcasts during your commute.",
    "Don't confuse your income with your wealth.",
    "Stop trying to keep up with the Joneses. The Joneses are broke.",
    "Wealth is what you don't see.",
    "Spending money to show people how much money you have is the fastest way to have less money.",
    "Don't be house poor. Keep your housing costs under 30% of your take-home pay.",
    "Renting is not \"throwing money away.\" It buys flexibility.",
    "Buy the worst house in the best neighborhood, not the best house in the worst.",
    "Always get a home inspection before buying.",
    "Save for a 20% down payment to avoid PMI.",
    "Understand exactly what your health insurance covers.",
    "Contribute enough to your 401(k) to get the full employer match.",
    "Increase your savings rate by 1% every couple of months.",
    "A 1% difference in investment fees can cost you hundreds of thousands over a lifetime.",
    "Use low-cost index funds instead of actively managed mutual funds.",
    "Don't let fear dictate your investment strategy.",
    "Don't try to catch a falling knife in the stock market.",
    "Past performance is not indicative of future results.",
    "You don't need a financial advisor until your situation is complex.",
    "If an advisor is commission-based, they are a salesperson, not a fiduciary.",
    "Always ask: \"How do you get paid?\"",
    "Protect your digital identity with a password manager.",
    "Freeze your credit if you suspect identity theft.",
    "Don't fall for phishing scams. Banks won't ask for your password.",
    "Check your bank statements for unauthorized charges monthly.",
    "Use two-factor authentication on all financial accounts.",
    "Make time to organize your financial documents.",
    "Keep digital backups of important financial records.",
    "Have a 'break glass in case of emergency' folder for your family.",
    "Don't ignore the math of your life.",
    "Small choices repeated over time yield massive results.",
    "The goal isn't more money. The goal is living life on your terms."
  ];
}
